python 01_ItemGenerator.py
python 03_ManifestGeneratorFromItems.py
python 11_PropertiesGenerator.py
python 12_ItemSetsGenerator.py
python 13_ResourceTemplatesGenerator.py
python 14_SitesGenerator.py
python 21_MediaGenerator.py
# python 31_FileDownloader.py